spring.application.name=ProductManagement

# C?u hình H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# C?u hình Datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# C?u hình JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false