CREATE TABLE `GROUPS` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE `CONTACT_GROUPS` (
    CONTACT_ID INT NOT NULL,
    GROUP_ID INT NOT NULL,
    PRIMARY KEY (CONTACT_ID, GROUP_ID),
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS`(ID) ON DELETE CASCADE
);
